### ISSUE TITLE
invalid flag-list

### ISSUE THREAD

**Issue by Eguthrie3214** [ruby/net-imap#228]
After updating from 0.4.1 to 0.4.3 we noticed errors when running a test that selects an inbox

> rails aborted!
Net::IMAP::ResponseParseError: invalid flag-list
/Users/evanguthrie/.rvm/gems/ruby-3.1.0@v3-workflows/gems/net-imap-0.4.3/lib/net/imap/response_parser/parser_utils.rb:234:in `parse_error'
/Users/evanguthrie/.rvm/gems/ruby-3.1.0@v3-workflows/gems/net-imap-0.4.3/lib/net/imap/response_parser/parser_utils.rb:205:in `match_re'
/Users/evanguthrie/.rvm/gems/ruby-3.1.0@v3-workflows/gems/net-imap-0.4.3/lib/net/imap/response_parser.rb:1713:in `flag_list'
/Users/evanguthrie/.rvm/gems/ruby-3.1.0@v3-workflows/gems/net-imap-0.4.3/lib/net/imap/response_parser.rb:1155:in `mailbox_data__flags'
/Users/evanguthrie/.rvm/gems/ruby-3.1.0@v3-workflows/gems/net-imap-0.4.3/lib/net/imap/response_parser.rb:571:in `response_data'

I was able to track this down to #212 and the change to flag parsing. 

Given the same input of 
![Screenshot 2023-11-13 at 2 51 40 PM](https://github.com/ruby/net-imap/assets/16674204/973b96b7-cdd6-4697-82fb-8081a588a7d1)
 for both versions, 0.4.3 fails

If it helps the combo of services im using looks like this 

```
version: '3'

services:

  db:
    image: postgres
    ports:
      - "6099:5432"
    environment:
      - POSTGRES_USER=workflows
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "7099:6379"

  mail:
    image: greenmail/standalone
    ports:
      - "3465:3465" #SMTPS
      - "3993:3993" #IMAPS
      - "3025:3025" #SMTP
      - "3143:3143" #IMAP
  roundcube:
    image: roundcube/roundcubemail:latest
    depends_on:
      - mail
    ports:
      - "8000:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail  # IMAP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143               # IMAP port
      - ROUNDCUBEMAIL_SMTP_SERVER=mail  # SMTP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS
      - ROUNDCUBEMAIL_SMTP_PORT=3025
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"

volumes:
  postgres-data:
  dynamodb-data:
``` 

and for an example of what im running to trigger this
```ruby
    puts imap.list("", "*")
    imap.select("INBOX")
``` 
imap is an instance of the imap client
The list command works, but it breaks during the select.  

Thank you for the time and I would be happy to provide more information!
